<#
  convert-curve.ps1
  Infomax IMDH 국고 민평 커브 xlsx -> data/ktb-curve.js

  - Excel COM 미사용 (xlsx = zip + OpenXML, .NET만으로 처리)
  - 파일이 Excel에서 열려 있어도 마지막 저장본을 읽음
  - 출력은 LF 개행, UTF-8 no BOM
  - 입력 파일이 없으면 조용히 종료 (개인 노트북에서 실행 시)

  사용:  powershell -NoProfile -ExecutionPolicy Bypass -File tools\convert-curve.ps1
#>

[CmdletBinding()]
param(
  [string]$InPath  = "_local\curve-data.xlsx",
  [string]$OutPath = "data\ktb-curve.js",
  [string]$Sheet   = "xl/worksheets/sheet1.xml"
)

$ErrorActionPreference = "Stop"

# 스크립트 위치 기준 -> 레포 루트로 이동
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

if (-not (Test-Path $InPath)) {
  Write-Host "[curve] 입력 파일 없음, 건너뜀: $InPath"
  exit 0
}

Add-Type -AssemblyName System.IO.Compression.FileSystem

# --- 만기 격자 (IMDH 컬럼 B..Q 순서와 반드시 일치해야 함) ---
$GRID = @(0.25,0.5,0.75,1,1.5,2,2.5,3,4,5,7,10,15,20,30,50)
$NCOL = $GRID.Count + 1          # 날짜 + 16개 = 17
$HEADER_ROW = 3                  # 3행이 헤더, 4행부터 데이터

# --- 헤더 검증용 기대 문자열 ---
$EXPECT = @('3월이하','6월이하','9월이하','1년이하','1.5년이하','2년이하','2.5년이하','3년이하',
            '4년이하','5년이하','7년이하','10년이하','15년이하','20년이하','30년이하','50년이하')

# --- xlsx 열기 ---
$full = (Resolve-Path $InPath).Path
$zip  = [System.IO.Compression.ZipFile]::OpenRead($full)
try {
  function Read-Entry([string]$name) {
    $e = $zip.Entries | Where-Object { $_.FullName -eq $name }
    if (-not $e) { throw "엔트리 없음: $name" }
    $sr = New-Object System.IO.StreamReader($e.Open(), [System.Text.Encoding]::UTF8)
    try { $sr.ReadToEnd() } finally { $sr.Dispose() }
  }

  $xmlSheet = Read-Entry $Sheet

  # sharedStrings (헤더 검증용)
  $shared = @()
  if ($zip.Entries | Where-Object { $_.FullName -eq 'xl/sharedStrings.xml' }) {
    $ss = Read-Entry 'xl/sharedStrings.xml'
    $shared = [regex]::Matches($ss, '<si>(?:(?!</si>).)*?</si>', 'Singleline') | ForEach-Object {
      ($_.Value | Select-String -Pattern '<t[^>]*>([^<]*)</t>' -AllMatches).Matches |
        ForEach-Object { $_.Groups[1].Value }
    } | ForEach-Object { $_ -join '' }
  }
}
finally { }

# --- 행 파싱 ---
$rowRx  = [regex]'<row r="(\d+)"[^>]*>(.*?)</row>'
$cellRx = [regex]'<c r="([A-Z]+)\d+"[^>]*?(?:/>|>(.*?)</c>)'
$vRx    = [regex]'<v>([^<]*)</v>'

function ColIndex([string]$letters) {
  $n = 0
  foreach ($ch in $letters.ToCharArray()) { $n = $n * 26 + ([int][char]$ch - 64) }
  return $n
}

$inv   = [System.Globalization.CultureInfo]::InvariantCulture
$lines = New-Object System.Collections.Generic.List[string]
$count = 0
$headerChecked = $false

foreach ($m in $rowRx.Matches($xmlSheet)) {
  $r = [int]$m.Groups[1].Value

  # 헤더 검증 (1회)
  if ($r -eq $HEADER_ROW -and -not $headerChecked) {
    $hdr = @{}
    foreach ($c in $cellRx.Matches($m.Groups[2].Value)) {
      $ci = ColIndex $c.Groups[1].Value
      $vm = $vRx.Match($c.Groups[2].Value)
      if ($vm.Success -and $ci -ge 2 -and $ci -le $NCOL) {
        $idx = [int]$vm.Groups[1].Value
        if ($idx -lt $shared.Count) { $hdr[$ci] = $shared[$idx] }
      }
    }
    for ($i = 2; $i -le $NCOL; $i++) {
      $got = $hdr[$i]
      $exp = $EXPECT[$i - 2]
      if ($got -and ($got -notlike "$exp*")) {
        throw "[curve] 컬럼 불일치: $i 번째 열이 '$got' 인데 '$exp' 를 기대함. GRID 정의를 확인하십시오."
      }
    }
    $headerChecked = $true
    continue
  }
  if ($r -lt 4) { continue }

  $cells = $cellRx.Matches($m.Groups[2].Value)
  if ($cells.Count -lt $NCOL) { continue }     # 빈 행 스킵

  $vals = New-Object string[] $NCOL
  $ok = $true
  foreach ($c in $cells) {
    $ci = ColIndex $c.Groups[1].Value
    if ($ci -lt 1 -or $ci -gt $NCOL) { continue }
    $vm = $vRx.Match($c.Groups[2].Value)
    if (-not $vm.Success) { continue }
    $raw = [double]::Parse($vm.Groups[1].Value, $inv)

    if ($ci -eq 1) {
      if ($raw -lt 1) { $ok = $false; break }
      $vals[0] = '"' + [datetime]::FromOADate($raw).ToString('yyyy-MM-dd', $inv) + '"'
    } else {
      # 0 = 해당 만기 미존재 (예: 초기 구간의 50Y) -> null
      $vals[$ci - 1] = if ($raw -eq 0) { 'null' }
                       else { [math]::Round($raw, 3).ToString('0.###', $inv) }
    }
  }
  if (-not $ok -or -not $vals[0]) { continue }
  for ($i = 1; $i -lt $NCOL; $i++) { if (-not $vals[$i]) { $vals[$i] = 'null' } }

  $lines.Add('[' + ($vals -join ',') + ']')
  $count++
}

$zip.Dispose()

if ($count -eq 0) { throw "[curve] 데이터 행 0건. 시트 구조를 확인하십시오." }

# --- 출력 (LF, UTF-8 no BOM) ---
$gridStr = ($GRID | ForEach-Object { $_.ToString($inv) }) -join ','
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("// generated by tools/convert-curve.ps1 - do not edit by hand`n")
[void]$sb.Append("// source: 시가평가 3사평균 국고채권 (Infomax IMDH BONDAVG01)`n")
[void]$sb.Append("window.KTB_CURVE={`n")
[void]$sb.Append("grid:[$gridStr],`n")
[void]$sb.Append("rows:[`n")
[void]$sb.Append(($lines -join ",`n"))
[void]$sb.Append("`n]};`n")

$dir = Split-Path -Parent $OutPath
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

$tmp = "$OutPath.tmp"
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $repo $tmp), $sb.ToString(), $enc)
Move-Item -Force $tmp $OutPath

$first = $lines[0]      -replace '^\["([^"]+)".*', '$1'
$last  = $lines[-1]     -replace '^\["([^"]+)".*', '$1'
Write-Host "[curve] $count 행  ($first ~ $last)  ->  $OutPath"
